# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/ayieko/Projects And  Research/PycharmProjects/Eztv-torrent-scrapper/GUI/MainDesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 891, 91))
        self.groupBox.setObjectName("groupBox")
        self.getDataButton = QtWidgets.QPushButton(self.groupBox)
        self.getDataButton.setGeometry(QtCore.QRect(810, 30, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.getDataButton.setFont(font)
        self.getDataButton.setObjectName("getDataButton")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 788, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.enterCheck = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enterCheck.sizePolicy().hasHeightForWidth())
        self.enterCheck.setSizePolicy(sizePolicy)
        self.enterCheck.setMinimumSize(QtCore.QSize(361, 20))
        self.enterCheck.setChecked(True)
        self.enterCheck.setObjectName("enterCheck")
        self.horizontalLayout.addWidget(self.enterCheck)
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.chooseCheck = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseCheck.sizePolicy().hasHeightForWidth())
        self.chooseCheck.setSizePolicy(sizePolicy)
        self.chooseCheck.setMinimumSize(QtCore.QSize(345, 20))
        self.chooseCheck.setObjectName("chooseCheck")
        self.horizontalLayout.addWidget(self.chooseCheck)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 791, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titleEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.titleEdit.setMinimumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titleEdit.setFont(font)
        self.titleEdit.setObjectName("titleEdit")
        self.horizontalLayout_2.addWidget(self.titleEdit)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.titleCombo = QtWidgets.QComboBox(self.layoutWidget1)
        self.titleCombo.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleCombo.sizePolicy().hasHeightForWidth())
        self.titleCombo.setSizePolicy(sizePolicy)
        self.titleCombo.setMinimumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titleCombo.setFont(font)
        self.titleCombo.setObjectName("titleCombo")
        self.horizontalLayout_2.addWidget(self.titleCombo)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 891, 400))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 98, 871, 298))
        self.groupBox_3.setObjectName("groupBox_3")
        self.resutlTable = QtWidgets.QTableWidget(self.groupBox_3)
        self.resutlTable.setGeometry(QtCore.QRect(10, 20, 851, 274))
        self.resutlTable.setAutoScrollMargin(6)
        self.resutlTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.resutlTable.setObjectName("resutlTable")
        self.resutlTable.setColumnCount(4)
        self.resutlTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resutlTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resutlTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resutlTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resutlTable.setHorizontalHeaderItem(3, item)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 47, 871, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.seasonSpin = QtWidgets.QSpinBox(self.groupBox_4)
        self.seasonSpin.setGeometry(QtCore.QRect(80, 20, 61, 22))
        self.seasonSpin.setMinimum(1)
        self.seasonSpin.setMaximum(99)
        self.seasonSpin.setObjectName("seasonSpin")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(170, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.episodeSpin = QtWidgets.QSpinBox(self.groupBox_4)
        self.episodeSpin.setGeometry(QtCore.QRect(230, 20, 61, 22))
        self.episodeSpin.setMinimum(1)
        self.episodeSpin.setMaximum(500)
        self.episodeSpin.setObjectName("episodeSpin")
        self.searchButton = QtWidgets.QPushButton(self.groupBox_4)
        self.searchButton.setGeometry(QtCore.QRect(560, 14, 111, 31))
        self.searchButton.setObjectName("searchButton")
        self.sortValueCombo = QtWidgets.QComboBox(self.groupBox_4)
        self.sortValueCombo.setGeometry(QtCore.QRect(380, 20, 91, 22))
        self.sortValueCombo.setObjectName("sortValueCombo")
        self.sortValueCombo.addItem("")
        self.sortValueCombo.addItem("")
        self.sortValueCombo.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(320, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 20, 871, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.dataNameLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.dataNameLabel.setFont(font)
        self.dataNameLabel.setStyleSheet("color: rgb(170, 170, 0);")
        self.dataNameLabel.setText("")
        self.dataNameLabel.setObjectName("dataNameLabel")
        self.horizontalLayout_3.addWidget(self.dataNameLabel)
        self.moreInfoButton = QtWidgets.QPushButton(self.widget)
        self.moreInfoButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.moreInfoButton.setObjectName("moreInfoButton")
        self.horizontalLayout_3.addWidget(self.moreInfoButton)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.enterCheck.toggled['bool'].connect(self.titleEdit.setEnabled)
        self.chooseCheck.toggled['bool'].connect(self.titleCombo.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Download the Tv Show data Localy"))
        self.getDataButton.setText(_translate("MainWindow", "Get Data"))
        self.enterCheck.setText(_translate("MainWindow", "Enter Manualy"))
        self.chooseCheck.setText(_translate("MainWindow", "Select from list"))
        self.titleEdit.setPlaceholderText(_translate("MainWindow", "Enter Tv Show Title"))
        self.label.setText(_translate("MainWindow", "OR"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Choose the Season and/or Episode you want to get magnet liinks for..."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results :"))
        self.resutlTable.setSortingEnabled(True)
        item = self.resutlTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.resutlTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.resutlTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Seeders"))
        item = self.resutlTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Magnet Link"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Options: "))
        self.label_2.setText(_translate("MainWindow", "Season : "))
        self.label_3.setText(_translate("MainWindow", "Episode : "))
        self.searchButton.setText(_translate("MainWindow", "Search.."))
        self.sortValueCombo.setItemText(0, _translate("MainWindow", "Size"))
        self.sortValueCombo.setItemText(1, _translate("MainWindow", "Name"))
        self.sortValueCombo.setItemText(2, _translate("MainWindow", "Seeders"))
        self.label_4.setText(_translate("MainWindow", "Sort By: "))
        self.label_5.setText(_translate("MainWindow", "Current database: "))
        self.moreInfoButton.setText(_translate("MainWindow", "More Info."))
