# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/ayieko/Projects And  Research/PycharmProjects/Eztv-torrent-scrapper/GUI/MainDesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(910, 501)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 55, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.titleEdit = QtGui.QLineEdit(self.centralwidget)
        self.titleEdit.setGeometry(QtCore.QRect(20, 49, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titleEdit.setFont(font)
        self.titleEdit.setObjectName(_fromUtf8("titleEdit"))
        self.titleCombo = QtGui.QComboBox(self.centralwidget)
        self.titleCombo.setEnabled(False)
        self.titleCombo.setGeometry(QtCore.QRect(450, 50, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titleCombo.setFont(font)
        self.titleCombo.setObjectName(_fromUtf8("titleCombo"))
        self.getDataButton = QtGui.QPushButton(self.centralwidget)
        self.getDataButton.setGeometry(QtCore.QRect(820, 50, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.getDataButton.setFont(font)
        self.getDataButton.setObjectName(_fromUtf8("getDataButton"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 891, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(11, 10, 788, 31))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.enterCheck = QtGui.QRadioButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enterCheck.sizePolicy().hasHeightForWidth())
        self.enterCheck.setSizePolicy(sizePolicy)
        self.enterCheck.setMinimumSize(QtCore.QSize(361, 20))
        self.enterCheck.setChecked(True)
        self.enterCheck.setObjectName(_fromUtf8("enterCheck"))
        self.horizontalLayout.addWidget(self.enterCheck)
        spacerItem = QtGui.QSpacerItem(68, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.chooseCheck = QtGui.QRadioButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseCheck.sizePolicy().hasHeightForWidth())
        self.chooseCheck.setSizePolicy(sizePolicy)
        self.chooseCheck.setMinimumSize(QtCore.QSize(345, 20))
        self.chooseCheck.setObjectName(_fromUtf8("chooseCheck"))
        self.horizontalLayout.addWidget(self.chooseCheck)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 891, 371))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 80, 871, 281))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.resutlTable = QtGui.QTableWidget(self.groupBox_3)
        self.resutlTable.setGeometry(QtCore.QRect(10, 20, 851, 255))
        self.resutlTable.setAutoScrollMargin(6)
        self.resutlTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.resutlTable.setObjectName(_fromUtf8("resutlTable"))
        self.resutlTable.setColumnCount(4)
        self.resutlTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.resutlTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.resutlTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.resutlTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.resutlTable.setHorizontalHeaderItem(3, item)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 871, 51))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.seasonSpin = QtGui.QSpinBox(self.groupBox_4)
        self.seasonSpin.setGeometry(QtCore.QRect(80, 20, 61, 22))
        self.seasonSpin.setMinimum(1)
        self.seasonSpin.setMaximum(99)
        self.seasonSpin.setObjectName(_fromUtf8("seasonSpin"))
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(170, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.episodeSpin = QtGui.QSpinBox(self.groupBox_4)
        self.episodeSpin.setGeometry(QtCore.QRect(230, 20, 61, 22))
        self.episodeSpin.setMinimum(1)
        self.episodeSpin.setMaximum(500)
        self.episodeSpin.setObjectName(_fromUtf8("episodeSpin"))
        self.searchButton = QtGui.QPushButton(self.groupBox_4)
        self.searchButton.setGeometry(QtCore.QRect(510, 20, 111, 25))
        self.searchButton.setObjectName(_fromUtf8("searchButton"))
        self.sortValueCombo = QtGui.QComboBox(self.groupBox_4)
        self.sortValueCombo.setGeometry(QtCore.QRect(380, 20, 91, 22))
        self.sortValueCombo.setObjectName(_fromUtf8("sortValueCombo"))
        self.sortValueCombo.addItem(_fromUtf8(""))
        self.sortValueCombo.addItem(_fromUtf8(""))
        self.sortValueCombo.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(320, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.groupBox.raise_()
        self.getDataButton.raise_()
        self.titleEdit.raise_()
        self.label.raise_()
        self.titleCombo.raise_()
        self.groupBox_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.enterCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.titleEdit.setEnabled)
        QtCore.QObject.connect(self.chooseCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.titleCombo.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "OR", None))
        self.titleEdit.setPlaceholderText(_translate("MainWindow", "Enter Tv Show Title", None))
        self.getDataButton.setText(_translate("MainWindow", "Get Data", None))
        self.groupBox.setTitle(_translate("MainWindow", "Download the Tv Show data Localy", None))
        self.enterCheck.setText(_translate("MainWindow", "Enter Manualy", None))
        self.chooseCheck.setText(_translate("MainWindow", "Select from list", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Choose the Season and/or Episode you want to get magnet liinks for...", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results :", None))
        item = self.resutlTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.resutlTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.resutlTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Seeders", None))
        item = self.resutlTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Magnet Link", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Options: ", None))
        self.label_2.setText(_translate("MainWindow", "Season : ", None))
        self.label_3.setText(_translate("MainWindow", "Episode : ", None))
        self.searchButton.setText(_translate("MainWindow", "Search..", None))
        self.sortValueCombo.setItemText(0, _translate("MainWindow", "Size", None))
        self.sortValueCombo.setItemText(1, _translate("MainWindow", "Name", None))
        self.sortValueCombo.setItemText(2, _translate("MainWindow", "Seeders", None))
        self.label_4.setText(_translate("MainWindow", "Sort By: ", None))

