# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/royalstate/Projects and Research/Python Projects/Eztv-torrent-scrapper/GUI/utils/design_files/MainDesign.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(915, 594)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imgs/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.enterCheck = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enterCheck.sizePolicy().hasHeightForWidth())
        self.enterCheck.setSizePolicy(sizePolicy)
        self.enterCheck.setMinimumSize(QtCore.QSize(361, 20))
        self.enterCheck.setChecked(True)
        self.enterCheck.setObjectName("enterCheck")
        self.horizontalLayout.addWidget(self.enterCheck)
        spacerItem = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.chooseCheck = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseCheck.sizePolicy().hasHeightForWidth())
        self.chooseCheck.setSizePolicy(sizePolicy)
        self.chooseCheck.setMinimumSize(QtCore.QSize(424, 20))
        self.chooseCheck.setObjectName("chooseCheck")
        self.horizontalLayout.addWidget(self.chooseCheck)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titleEdit = QtWidgets.QLineEdit(self.groupBox)
        self.titleEdit.setMinimumSize(QtCore.QSize(392, 30))
        self.titleEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titleEdit.setFont(font)
        self.titleEdit.setToolTip("")
        self.titleEdit.setObjectName("titleEdit")
        self.horizontalLayout_2.addWidget(self.titleEdit)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.titleCombo = QtWidgets.QComboBox(self.groupBox)
        self.titleCombo.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleCombo.sizePolicy().hasHeightForWidth())
        self.titleCombo.setSizePolicy(sizePolicy)
        self.titleCombo.setMinimumSize(QtCore.QSize(430, 30))
        self.titleCombo.setMaximumSize(QtCore.QSize(430, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titleCombo.setFont(font)
        self.titleCombo.setObjectName("titleCombo")
        self.horizontalLayout_2.addWidget(self.titleCombo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setMinimumSize(QtCore.QSize(0, 15))
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 15))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.searchForCombo = QtWidgets.QComboBox(self.groupBox)
        self.searchForCombo.setMinimumSize(QtCore.QSize(100, 20))
        self.searchForCombo.setMaximumSize(QtCore.QSize(100, 20))
        self.searchForCombo.setObjectName("searchForCombo")
        self.searchForCombo.addItem("")
        self.searchForCombo.addItem("")
        self.searchForCombo.addItem("")
        self.searchForCombo.addItem("")
        self.searchForCombo.addItem("")
        self.horizontalLayout_6.addWidget(self.searchForCombo)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.scraperCombo = QtWidgets.QComboBox(self.groupBox)
        self.scraperCombo.setMinimumSize(QtCore.QSize(100, 20))
        self.scraperCombo.setMaximumSize(QtCore.QSize(100, 20))
        self.scraperCombo.setObjectName("scraperCombo")
        self.scraperCombo.addItem("")
        self.scraperCombo.addItem("")
        self.scraperCombo.addItem("")
        self.scraperCombo.addItem("")
        self.horizontalLayout_6.addWidget(self.scraperCombo)
        spacerItem1 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.showStatusCheck = QtWidgets.QCheckBox(self.groupBox)
        self.showStatusCheck.setObjectName("showStatusCheck")
        self.horizontalLayout_6.addWidget(self.showStatusCheck)
        self.getDataButton = QtWidgets.QPushButton(self.groupBox)
        self.getDataButton.setMinimumSize(QtCore.QSize(200, 25))
        self.getDataButton.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.getDataButton.setFont(font)
        self.getDataButton.setDefault(True)
        self.getDataButton.setObjectName("getDataButton")
        self.horizontalLayout_6.addWidget(self.getDataButton)
        self.stopGetDataButton = QtWidgets.QPushButton(self.groupBox)
        self.stopGetDataButton.setEnabled(False)
        self.stopGetDataButton.setMinimumSize(QtCore.QSize(40, 23))
        self.stopGetDataButton.setMaximumSize(QtCore.QSize(40, 23))
        self.stopGetDataButton.setObjectName("stopGetDataButton")
        self.horizontalLayout_6.addWidget(self.stopGetDataButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10.addWidget(self.groupBox)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_6)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_8.setSpacing(3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(120, 20))
        self.label_5.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.dataNameLabel = QtWidgets.QLabel(self.groupBox_2)
        self.dataNameLabel.setMinimumSize(QtCore.QSize(500, 20))
        self.dataNameLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.dataNameLabel.setFont(font)
        self.dataNameLabel.setStyleSheet("color: rgb(170, 170, 0);")
        self.dataNameLabel.setText("")
        self.dataNameLabel.setObjectName("dataNameLabel")
        self.horizontalLayout_3.addWidget(self.dataNameLabel)
        self.moreInfoButton = QtWidgets.QPushButton(self.groupBox_2)
        self.moreInfoButton.setMinimumSize(QtCore.QSize(75, 20))
        self.moreInfoButton.setMaximumSize(QtCore.QSize(150, 20))
        self.moreInfoButton.setObjectName("moreInfoButton")
        self.horizontalLayout_3.addWidget(self.moreInfoButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.seasonCheck = QtWidgets.QCheckBox(self.groupBox_4)
        self.seasonCheck.setMinimumSize(QtCore.QSize(55, 22))
        self.seasonCheck.setMaximumSize(QtCore.QSize(55, 22))
        self.seasonCheck.setChecked(True)
        self.seasonCheck.setObjectName("seasonCheck")
        self.horizontalLayout_4.addWidget(self.seasonCheck)
        self.seasonSpin = QtWidgets.QSpinBox(self.groupBox_4)
        self.seasonSpin.setEnabled(True)
        self.seasonSpin.setMinimumSize(QtCore.QSize(50, 22))
        self.seasonSpin.setMaximumSize(QtCore.QSize(50, 22))
        self.seasonSpin.setMinimum(1)
        self.seasonSpin.setMaximum(99)
        self.seasonSpin.setProperty("value", 1)
        self.seasonSpin.setObjectName("seasonSpin")
        self.horizontalLayout_4.addWidget(self.seasonSpin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.episodeCheck = QtWidgets.QCheckBox(self.groupBox_4)
        self.episodeCheck.setMinimumSize(QtCore.QSize(55, 22))
        self.episodeCheck.setMaximumSize(QtCore.QSize(55, 22))
        self.episodeCheck.setChecked(True)
        self.episodeCheck.setObjectName("episodeCheck")
        self.horizontalLayout_7.addWidget(self.episodeCheck)
        self.episodeSpin = QtWidgets.QSpinBox(self.groupBox_4)
        self.episodeSpin.setEnabled(True)
        self.episodeSpin.setMinimumSize(QtCore.QSize(50, 22))
        self.episodeSpin.setMaximumSize(QtCore.QSize(50, 22))
        self.episodeSpin.setMinimum(1)
        self.episodeSpin.setMaximum(500)
        self.episodeSpin.setObjectName("episodeSpin")
        self.horizontalLayout_7.addWidget(self.episodeSpin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.searchTermCheck = QtWidgets.QCheckBox(self.groupBox_4)
        self.searchTermCheck.setMinimumSize(QtCore.QSize(80, 22))
        self.searchTermCheck.setMaximumSize(QtCore.QSize(80, 22))
        self.searchTermCheck.setObjectName("searchTermCheck")
        self.horizontalLayout_10.addWidget(self.searchTermCheck)
        self.searchTermEntry = QtWidgets.QLineEdit(self.groupBox_4)
        self.searchTermEntry.setEnabled(False)
        self.searchTermEntry.setMinimumSize(QtCore.QSize(170, 23))
        self.searchTermEntry.setMaximumSize(QtCore.QSize(200, 23))
        self.searchTermEntry.setObjectName("searchTermEntry")
        self.horizontalLayout_10.addWidget(self.searchTermEntry)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setMinimumSize(QtCore.QSize(53, 25))
        self.label_4.setMaximumSize(QtCore.QSize(20, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.sortValueCombo = QtWidgets.QComboBox(self.groupBox_4)
        self.sortValueCombo.setMinimumSize(QtCore.QSize(81, 25))
        self.sortValueCombo.setMaximumSize(QtCore.QSize(80, 25))
        self.sortValueCombo.setObjectName("sortValueCombo")
        self.sortValueCombo.addItem("")
        self.sortValueCombo.addItem("")
        self.sortValueCombo.addItem("")
        self.horizontalLayout_5.addWidget(self.sortValueCombo)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(self.groupBox_4)
        self.line.setMinimumSize(QtCore.QSize(5, 25))
        self.line.setMaximumSize(QtCore.QSize(5, 25))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_11.addWidget(self.line)
        self.displayAllCheck = QtWidgets.QCheckBox(self.groupBox_4)
        self.displayAllCheck.setMinimumSize(QtCore.QSize(80, 22))
        self.displayAllCheck.setMaximumSize(QtCore.QSize(100, 22))
        self.displayAllCheck.setObjectName("displayAllCheck")
        self.horizontalLayout_11.addWidget(self.displayAllCheck)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.line_2 = QtWidgets.QFrame(self.groupBox_4)
        self.line_2.setMinimumSize(QtCore.QSize(0, 60))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_12.addWidget(self.line_2)
        self.searchButton = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setMinimumSize(QtCore.QSize(100, 35))
        self.searchButton.setMaximumSize(QtCore.QSize(150, 35))
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_12.addWidget(self.searchButton)
        self.toolButton = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton.setMinimumSize(QtCore.QSize(20, 15))
        self.toolButton.setMaximumSize(QtCore.QSize(20, 15))
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_12.addWidget(self.toolButton)
        self.verticalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_8.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_8.setSpacing(2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.stackedWidget = QtWidgets.QStackedWidget(self.groupBox_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.showResutlTable = QtWidgets.QTableWidget(self.page)
        self.showResutlTable.setAutoScrollMargin(6)
        self.showResutlTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.showResutlTable.setObjectName("showResutlTable")
        self.showResutlTable.setColumnCount(4)
        self.showResutlTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.showResutlTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.showResutlTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.showResutlTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.showResutlTable.setHorizontalHeaderItem(3, item)
        self.showResutlTable.horizontalHeader().setMinimumSectionSize(100)
        self.verticalLayout_5.addWidget(self.showResutlTable)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.moviesResutlTable = QtWidgets.QTableWidget(self.page_2)
        self.moviesResutlTable.setAutoScrollMargin(6)
        self.moviesResutlTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.moviesResutlTable.setObjectName("moviesResutlTable")
        self.moviesResutlTable.setColumnCount(4)
        self.moviesResutlTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.moviesResutlTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.moviesResutlTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.moviesResutlTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.moviesResutlTable.setHorizontalHeaderItem(3, item)
        self.moviesResutlTable.horizontalHeader().setMinimumSectionSize(100)
        self.horizontalLayout_9.addWidget(self.moviesResutlTable)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.animeResutlTable = QtWidgets.QTableWidget(self.page_3)
        self.animeResutlTable.setAutoScrollMargin(6)
        self.animeResutlTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.animeResutlTable.setObjectName("animeResutlTable")
        self.animeResutlTable.setColumnCount(4)
        self.animeResutlTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.animeResutlTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.animeResutlTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.animeResutlTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.animeResutlTable.setHorizontalHeaderItem(3, item)
        self.animeResutlTable.horizontalHeader().setMinimumSectionSize(100)
        self.verticalLayout_6.addWidget(self.animeResutlTable)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.subtitleResutlTable = QtWidgets.QTableWidget(self.page_4)
        self.subtitleResutlTable.setAutoScrollMargin(6)
        self.subtitleResutlTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.subtitleResutlTable.setObjectName("subtitleResutlTable")
        self.subtitleResutlTable.setColumnCount(4)
        self.subtitleResutlTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.subtitleResutlTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.subtitleResutlTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.subtitleResutlTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.subtitleResutlTable.setHorizontalHeaderItem(3, item)
        self.subtitleResutlTable.horizontalHeader().setMinimumSectionSize(100)
        self.verticalLayout_7.addWidget(self.subtitleResutlTable)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.searchAllTable = QtWidgets.QTableWidget(self.page_5)
        self.searchAllTable.setAutoScrollMargin(6)
        self.searchAllTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.searchAllTable.setObjectName("searchAllTable")
        self.searchAllTable.setColumnCount(4)
        self.searchAllTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.searchAllTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchAllTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchAllTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchAllTable.setHorizontalHeaderItem(3, item)
        self.searchAllTable.horizontalHeader().setMinimumSectionSize(100)
        self.verticalLayout_9.addWidget(self.searchAllTable)
        self.stackedWidget.addWidget(self.page_5)
        self.horizontalLayout_8.addWidget(self.stackedWidget)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_7)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.loggingConsole = QtWidgets.QTextBrowser(self.page_7)
        self.loggingConsole.setObjectName("loggingConsole")
        self.horizontalLayout_13.addWidget(self.loggingConsole)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.backButton = QtWidgets.QPushButton(self.page_7)
        self.backButton.setObjectName("backButton")
        self.verticalLayout_11.addWidget(self.backButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_11.addItem(spacerItem6)
        self.autoScroll = QtWidgets.QCheckBox(self.page_7)
        self.autoScroll.setObjectName("autoScroll")
        self.verticalLayout_11.addWidget(self.autoScroll)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem7)
        self.horizontalLayout_13.addLayout(self.verticalLayout_11)
        self.stackedWidget_2.addWidget(self.page_7)
        self.verticalLayout_10.addWidget(self.stackedWidget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.enterCheck.toggled['bool'].connect(self.titleEdit.setEnabled)
        self.chooseCheck.toggled['bool'].connect(self.titleCombo.setEnabled)
        self.chooseCheck.toggled['bool'].connect(self.titleEdit.setDisabled)
        self.searchForCombo.currentIndexChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        self.seasonCheck.toggled['bool'].connect(self.seasonSpin.setEnabled)
        self.episodeCheck.toggled['bool'].connect(self.episodeSpin.setEnabled)
        self.searchTermCheck.toggled['bool'].connect(self.searchTermEntry.setEnabled)
        self.displayAllCheck.clicked['bool'].connect(self.seasonCheck.setDisabled)
        self.displayAllCheck.clicked['bool'].connect(self.episodeCheck.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.getDataButton, self.searchButton)
        MainWindow.setTabOrder(self.searchButton, self.titleCombo)
        MainWindow.setTabOrder(self.titleCombo, self.enterCheck)
        MainWindow.setTabOrder(self.enterCheck, self.titleEdit)
        MainWindow.setTabOrder(self.titleEdit, self.chooseCheck)
        MainWindow.setTabOrder(self.chooseCheck, self.showResutlTable)
        MainWindow.setTabOrder(self.showResutlTable, self.searchForCombo)
        MainWindow.setTabOrder(self.searchForCombo, self.sortValueCombo)
        MainWindow.setTabOrder(self.sortValueCombo, self.episodeSpin)
        MainWindow.setTabOrder(self.episodeSpin, self.seasonSpin)
        MainWindow.setTabOrder(self.seasonSpin, self.moreInfoButton)
        MainWindow.setTabOrder(self.moreInfoButton, self.moviesResutlTable)
        MainWindow.setTabOrder(self.moviesResutlTable, self.toolButton)
        MainWindow.setTabOrder(self.toolButton, self.scraperCombo)
        MainWindow.setTabOrder(self.scraperCombo, self.animeResutlTable)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EZTV MOVIE TORRENT DOWNLOADER"))
        self.groupBox.setTitle(_translate("MainWindow", "Download the Tv Show data Localy"))
        self.enterCheck.setText(_translate("MainWindow", "Enter Manualy"))
        self.chooseCheck.setText(_translate("MainWindow", "Select from list"))
        self.titleEdit.setPlaceholderText(_translate("MainWindow", "Enter Tv Show Title"))
        self.label.setText(_translate("MainWindow", "OR"))
        self.titleCombo.setToolTip(_translate("MainWindow", "Select a title from well known titles"))
        self.label_6.setText(_translate("MainWindow", "Scrape for : "))
        self.searchForCombo.setToolTip(_translate("MainWindow", "Configure what I should serach for"))
        self.searchForCombo.setItemText(0, _translate("MainWindow", "TV-Show"))
        self.searchForCombo.setItemText(1, _translate("MainWindow", "Movie"))
        self.searchForCombo.setItemText(2, _translate("MainWindow", "Anime"))
        self.searchForCombo.setItemText(3, _translate("MainWindow", "Subtitles"))
        self.searchForCombo.setItemText(4, _translate("MainWindow", "All Categories"))
        self.label_7.setText(_translate("MainWindow", "Scrape from : "))
        self.scraperCombo.setToolTip(_translate("MainWindow", "The site where I should look for torrents from."))
        self.scraperCombo.setItemText(0, _translate("MainWindow", "EZTV"))
        self.scraperCombo.setItemText(1, _translate("MainWindow", "Kickass"))
        self.scraperCombo.setItemText(2, _translate("MainWindow", "The Pirate Bay"))
        self.scraperCombo.setItemText(3, _translate("MainWindow", "All Sites"))
        self.showStatusCheck.setText(_translate("MainWindow", "Show Status"))
        self.getDataButton.setToolTip(_translate("MainWindow", "Download the torrent links for the selected Series OR movie"))
        self.getDataButton.setWhatsThis(_translate("MainWindow", "Download the torrent links for the selected Series OR movie"))
        self.getDataButton.setText(_translate("MainWindow", "Get Data"))
        self.stopGetDataButton.setText(_translate("MainWindow", "Stop"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Choose the Season and Episode you want to get magnet links for..."))
        self.label_5.setText(_translate("MainWindow", "Current database: "))
        self.moreInfoButton.setToolTip(_translate("MainWindow", "See more information regarding the searched title online"))
        self.moreInfoButton.setText(_translate("MainWindow", "More Info..."))
        self.groupBox_4.setTitle(_translate("MainWindow", "Options: "))
        self.seasonCheck.setText(_translate("MainWindow", "Season"))
        self.seasonSpin.setToolTip(_translate("MainWindow", "Season to search for."))
        self.episodeCheck.setText(_translate("MainWindow", "Episode"))
        self.episodeSpin.setToolTip(_translate("MainWindow", "Episode to search for."))
        self.searchTermCheck.setText(_translate("MainWindow", "Search Term"))
        self.label_4.setText(_translate("MainWindow", "Sort By: "))
        self.sortValueCombo.setToolTip(_translate("MainWindow", "What should I use to sort the values"))
        self.sortValueCombo.setItemText(0, _translate("MainWindow", "Name"))
        self.sortValueCombo.setItemText(1, _translate("MainWindow", "Size"))
        self.sortValueCombo.setItemText(2, _translate("MainWindow", "Seeders"))
        self.displayAllCheck.setText(_translate("MainWindow", "Display All"))
        self.searchButton.setToolTip(_translate("MainWindow", "Search for an title\'s download link(magnet link) from the localy available database."))
        self.searchButton.setStatusTip(_translate("MainWindow", "Search"))
        self.searchButton.setText(_translate("MainWindow", "Search.."))
        self.toolButton.setToolTip(_translate("MainWindow", "Online Search settings"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results :"))
        item = self.showResutlTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Show Name"))
        item = self.showResutlTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.showResutlTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Seeders"))
        item = self.showResutlTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Magnet Link"))
        item = self.moviesResutlTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Movie Name"))
        item = self.moviesResutlTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.moviesResutlTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Seeders"))
        item = self.moviesResutlTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Magnet Link"))
        item = self.animeResutlTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Anime Name"))
        item = self.animeResutlTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.animeResutlTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Seeders"))
        item = self.animeResutlTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Magnet Link"))
        item = self.subtitleResutlTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Subtitle Name"))
        item = self.subtitleResutlTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.subtitleResutlTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Seeders"))
        item = self.subtitleResutlTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Magnet Link"))
        item = self.searchAllTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Torrent Name"))
        item = self.searchAllTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.searchAllTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Seeders"))
        item = self.searchAllTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Magnet Link"))
        self.loggingConsole.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Welcome</p></body></html>"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.autoScroll.setText(_translate("MainWindow", "Auto Scroll"))
