# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ayieko/Projects And Research/Python Projects/Eztv-torrent-scrapper/GUI/utils/design_files/MainDesign.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/ayieko/Projects And Research/Python Projects/Eztv-torrent-scrapper/GUI/utils/design_files/../imgs/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 891, 127))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.enterCheck = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enterCheck.sizePolicy().hasHeightForWidth())
        self.enterCheck.setSizePolicy(sizePolicy)
        self.enterCheck.setMinimumSize(QtCore.QSize(361, 20))
        self.enterCheck.setChecked(True)
        self.enterCheck.setObjectName("enterCheck")
        self.horizontalLayout.addWidget(self.enterCheck)
        spacerItem = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.chooseCheck = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseCheck.sizePolicy().hasHeightForWidth())
        self.chooseCheck.setSizePolicy(sizePolicy)
        self.chooseCheck.setMinimumSize(QtCore.QSize(424, 20))
        self.chooseCheck.setObjectName("chooseCheck")
        self.horizontalLayout.addWidget(self.chooseCheck)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titleEdit = QtWidgets.QLineEdit(self.groupBox)
        self.titleEdit.setMinimumSize(QtCore.QSize(392, 30))
        self.titleEdit.setMaximumSize(QtCore.QSize(390, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titleEdit.setFont(font)
        self.titleEdit.setObjectName("titleEdit")
        self.horizontalLayout_2.addWidget(self.titleEdit)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.titleCombo = QtWidgets.QComboBox(self.groupBox)
        self.titleCombo.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleCombo.sizePolicy().hasHeightForWidth())
        self.titleCombo.setSizePolicy(sizePolicy)
        self.titleCombo.setMinimumSize(QtCore.QSize(437, 30))
        self.titleCombo.setMaximumSize(QtCore.QSize(390, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titleCombo.setFont(font)
        self.titleCombo.setObjectName("titleCombo")
        self.horizontalLayout_2.addWidget(self.titleCombo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.getDataButton = QtWidgets.QPushButton(self.groupBox)
        self.getDataButton.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.getDataButton.setFont(font)
        self.getDataButton.setObjectName("getDataButton")
        self.verticalLayout.addWidget(self.getDataButton)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 893, 421))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 118, 891, 311))
        self.groupBox_3.setObjectName("groupBox_3")
        self.resutlTable = QtWidgets.QTableWidget(self.groupBox_3)
        self.resutlTable.setGeometry(QtCore.QRect(0, 30, 881, 271))
        self.resutlTable.setAutoScrollMargin(6)
        self.resutlTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.resutlTable.setObjectName("resutlTable")
        self.resutlTable.setColumnCount(4)
        self.resutlTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resutlTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resutlTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resutlTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resutlTable.setHorizontalHeaderItem(3, item)
        self.resutlTable.horizontalHeader().setMinimumSectionSize(100)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 47, 881, 67))
        self.groupBox_4.setObjectName("groupBox_4")
        self.searchButton = QtWidgets.QPushButton(self.groupBox_4)
        self.searchButton.setGeometry(QtCore.QRect(760, 27, 85, 27))
        self.searchButton.setObjectName("searchButton")
        self.line = QtWidgets.QFrame(self.groupBox_4)
        self.line.setGeometry(QtCore.QRect(253, 25, 16, 31))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.toolButton = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton.setGeometry(QtCore.QRect(850, 27, 25, 27))
        self.toolButton.setObjectName("toolButton")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(430, 25, 185, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setMinimumSize(QtCore.QSize(77, 0))
        self.label_6.setMaximumSize(QtCore.QSize(77, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.searchForCombo = QtWidgets.QComboBox(self.layoutWidget_2)
        self.searchForCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.searchForCombo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.searchForCombo.setObjectName("searchForCombo")
        self.searchForCombo.addItem("")
        self.searchForCombo.addItem("")
        self.searchForCombo.addItem("")
        self.horizontalLayout_6.addWidget(self.searchForCombo)
        self.line_2 = QtWidgets.QFrame(self.groupBox_4)
        self.line_2.setGeometry(QtCore.QRect(413, 25, 16, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.groupBox_4)
        self.line_3.setGeometry(QtCore.QRect(616, 25, 16, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setGeometry(QtCore.QRect(10, 25, 241, 32))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.season_episodeRadio = QtWidgets.QRadioButton(self.widget)
        self.season_episodeRadio.setMinimumSize(QtCore.QSize(20, 24))
        self.season_episodeRadio.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.season_episodeRadio.setFont(font)
        self.season_episodeRadio.setText("")
        self.season_episodeRadio.setChecked(True)
        self.season_episodeRadio.setObjectName("season_episodeRadio")
        self.horizontalLayout_4.addWidget(self.season_episodeRadio)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.seasonSpin = QtWidgets.QSpinBox(self.widget)
        self.seasonSpin.setMinimumSize(QtCore.QSize(50, 30))
        self.seasonSpin.setMaximumSize(QtCore.QSize(50, 30))
        self.seasonSpin.setMinimum(1)
        self.seasonSpin.setMaximum(99)
        self.seasonSpin.setProperty("value", 1)
        self.seasonSpin.setObjectName("seasonSpin")
        self.horizontalLayout_4.addWidget(self.seasonSpin)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(55, 0))
        self.label_3.setMaximumSize(QtCore.QSize(55, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.episodeSpin = QtWidgets.QSpinBox(self.widget)
        self.episodeSpin.setMinimumSize(QtCore.QSize(50, 30))
        self.episodeSpin.setMaximumSize(QtCore.QSize(50, 30))
        self.episodeSpin.setMinimum(1)
        self.episodeSpin.setMaximum(500)
        self.episodeSpin.setObjectName("episodeSpin")
        self.horizontalLayout_4.addWidget(self.episodeSpin)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.widget1 = QtWidgets.QWidget(self.groupBox_4)
        self.widget1.setGeometry(QtCore.QRect(270, 25, 142, 31))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setMinimumSize(QtCore.QSize(53, 0))
        self.label_4.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.sortValueCombo = QtWidgets.QComboBox(self.widget1)
        self.sortValueCombo.setMinimumSize(QtCore.QSize(81, 0))
        self.sortValueCombo.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sortValueCombo.setObjectName("sortValueCombo")
        self.sortValueCombo.addItem("")
        self.sortValueCombo.addItem("")
        self.sortValueCombo.addItem("")
        self.horizontalLayout_5.addWidget(self.sortValueCombo)
        self.line.raise_()
        self.seasonSpin.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.episodeSpin.raise_()
        self.searchButton.raise_()
        self.sortValueCombo.raise_()
        self.label_4.raise_()
        self.toolButton.raise_()
        self.layoutWidget_2.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 871, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.dataNameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.dataNameLabel.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.dataNameLabel.setFont(font)
        self.dataNameLabel.setStyleSheet("color: rgb(170, 170, 0);")
        self.dataNameLabel.setText("")
        self.dataNameLabel.setObjectName("dataNameLabel")
        self.horizontalLayout_3.addWidget(self.dataNameLabel)
        self.moreInfoButton = QtWidgets.QPushButton(self.layoutWidget)
        self.moreInfoButton.setMaximumSize(QtCore.QSize(105, 16777215))
        self.moreInfoButton.setObjectName("moreInfoButton")
        self.horizontalLayout_3.addWidget(self.moreInfoButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.enterCheck.toggled['bool'].connect(self.titleEdit.setEnabled)
        self.chooseCheck.toggled['bool'].connect(self.titleCombo.setEnabled)
        self.chooseCheck.toggled['bool'].connect(self.titleEdit.setDisabled)
        self.season_episodeRadio.toggled['bool'].connect(self.seasonSpin.setEnabled)
        self.season_episodeRadio.toggled['bool'].connect(self.episodeSpin.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EZTV MOVIE TORRENT DOWNLOADER"))
        self.groupBox.setTitle(_translate("MainWindow", "Download the Tv Show data Localy"))
        self.enterCheck.setText(_translate("MainWindow", "Enter Manualy"))
        self.chooseCheck.setText(_translate("MainWindow", "Select from list"))
        self.titleEdit.setPlaceholderText(_translate("MainWindow", "Enter Tv Show Title"))
        self.label.setText(_translate("MainWindow", "OR"))
        self.getDataButton.setToolTip(_translate("MainWindow", "Download the torrent links for the selected Series OR movie"))
        self.getDataButton.setWhatsThis(_translate("MainWindow", "Download the torrent links for the selected Series OR movie"))
        self.getDataButton.setText(_translate("MainWindow", "Get Data"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Choose the Season and/or Episode you want to get magnet or links for..."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results :"))
        self.resutlTable.setSortingEnabled(True)
        item = self.resutlTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.resutlTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.resutlTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Seeders"))
        item = self.resutlTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Magnet Link"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Options: "))
        self.searchButton.setToolTip(_translate("MainWindow", "Search for an title\'s download link(magnet link) from the localy available database."))
        self.searchButton.setText(_translate("MainWindow", "Search.."))
        self.toolButton.setToolTip(_translate("MainWindow", "Online Search settings"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate("MainWindow", "Search For.."))
        self.searchForCombo.setToolTip(_translate("MainWindow", "Configure what to search for"))
        self.searchForCombo.setItemText(0, _translate("MainWindow", "TV-Show"))
        self.searchForCombo.setItemText(1, _translate("MainWindow", "Movie"))
        self.searchForCombo.setItemText(2, _translate("MainWindow", "Subtitles"))
        self.label_2.setText(_translate("MainWindow", "Season : "))
        self.seasonSpin.setToolTip(_translate("MainWindow", "Season to search for."))
        self.label_3.setText(_translate("MainWindow", "Episode : "))
        self.episodeSpin.setToolTip(_translate("MainWindow", "Episode to search for."))
        self.label_4.setText(_translate("MainWindow", "Sort By: "))
        self.sortValueCombo.setItemText(0, _translate("MainWindow", "Size"))
        self.sortValueCombo.setItemText(1, _translate("MainWindow", "Name"))
        self.sortValueCombo.setItemText(2, _translate("MainWindow", "Seeders"))
        self.label_5.setText(_translate("MainWindow", "Current database: "))
        self.moreInfoButton.setToolTip(_translate("MainWindow", "See more information regarding the searched title online"))
        self.moreInfoButton.setText(_translate("MainWindow", "More Info..."))
